export const WIDTH_TO_MINUS = 36;
export const CONTENT_VIEW_OFFSET = WIDTH_TO_MINUS / 2.7;
export const AUTOPLAY_DURATION_MS = 3500; // millis
export const SCROLL_EVENT_THROTTLE = 32;
export const TOUCHABLE_ACTIVE_OPACITY = 0.9;
export const DOT_SIZE = 8;
export const DOT_INACTIVE_COLOR = "#758283";
export const DOT_ACTIVE_COLOR = "#ffffff";
export const DOT_CONTAINER_COLOR = "#00000070";